# Generated by Django 4.2.2 on 2023-06-24 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=datetime.date(2023, 6, 24)),
            preserve_default=False,
        ),
    ]
