# Generated by Django 4.2.2 on 2023-09-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user2',
        ),
    ]
