# Generated by Django 4.2.2 on 2023-09-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user2',
        ),
    ]
