# Generated by Django 4.2.2 on 2025-06-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_image_photo_alter_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="breeds",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
