# Generated by Django 4.2.2 on 2025-09-22 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0008_alter_post_breeds_alter_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="photo",
            field=models.ImageField(
                upload_to="pics/%Y/%m/%d/", validators=[post.models.validate_image_size]
            ),
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField()),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
