# Generated by Django 4.2.2 on 2025-09-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_approved_delete_approval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="approved",
            old_name="userID",
            new_name="user",
        ),
        migrations.AddField(
            model_name="approved",
            name="approved",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
