# Generated by Django 4.2.2 on 2025-09-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_rename_userid_approved_user_approved_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approved",
            name="user",
        ),
        migrations.AddField(
            model_name="approved",
            name="post",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="post.post"
            ),
            preserve_default=False,
        ),
    ]
