# Generated by Django 4.2.2 on 2023-06-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_remove_post_profile_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
