# Generated by Django 4.2.2 on 2023-07-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
