# Generated by Django 4.2.2 on 2023-09-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_user_post_user2'),
        ('user', '0003_delete_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
    ]
