# Generated by Django 4.2.2 on 2023-09-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
